name: afl3_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  double_back_to_close: ^2.0.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_spinkit: ^5.2.1
  equatable: ^2.0.5
  fluttertoast: ^8.2.8
  provider: ^6.0.5
  intl: ^0.20.0
  dropdown_button2: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

